### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pirelenito** [maxov/thome#1]
Hi there,

Loved your work on this!

Me and @xaviervia are working on a fun little side-project on procedural content, and we copied your names dictionary for our names procedural function (since you didn't publish it as an npm package).

We've add an [attribution](https://github.com/batata-frita/star-stuff/blob/master/packages/name/src/database.js) to your repo.

Let us know if you think that is fine, otherwise we can take it out and search for another source.

Cheers!

**Comment by maxov** [comment]
Your attribution looks fine, thank you for letting me know! I never licensed this because I figure no one would use it, but the fact that you found a use for it is awesome. I will put MIT on it now just to formalize things for anyone in the future.

**Comment by maxov** [comment]
I have added a license, see [here](https://github.com/maxov/thome/commit/da4a5fdb59dc56cdf634c141dc0f98260a5a30b6).

**Comment by xaviervia** [comment]
Awesome, thanks!
